data class Post(val id: Int = 1,
                val ownerId: Int,
                val authorId: Int,
                val createdBy: Int,
                val date: Int,
                val text: String,
                val replyOwnerId: Int,
                val replyPostId: Int,
                val friendsOnly: Boolean,
                val comments: Сomments,
                val copyright: Copyright,
                val likes: Likes,
                val  reposts: Reposts,
                val views: Views,
                val postType: String,
                val  signerId: Int,
                val canPin: Boolean,
                val canDelete: Boolean,
                val canEdit: Boolean,
                val isPinned: Boolean,
                val markedAsAds: Boolean,
                val isFavorite: Boolean,
                val donut: Donut,
                val postponedId: Int,
                val geo: Geo?,
                val postSource: postSource?,
                val attachments:Array<Attachment>?,
                val copyHistory:Array<Repost>?) {
}

